start:
  text: "С днем рождения, любимый! 🎉 Сегодня тебя ждет милый квест 💌"
  buttons:
    - text: "Продолжить"
      next: q1

q1:
  text: "Что бы ты хотел делать в первую очередь, когда мы встретимся? 😉"
  buttons:
    - text: "Обнимашки"
      reply: "Я бы тоже очень хотела тебя сейчас обнять. Утонуть в тепле и уюте🫂"
    - text: "Рассказывать все новости"
      reply: "Мы можем разговаривать часами напролет, но и молчать нам комфортно🤫"
    - text: "Очень много гулять"
      reply: "Гулять так, что ноги отваливаются. Такое одобряем😃"
    - text: "Смотреть в глаза"
      reply: "Давно я их не видела, надо исправлять💔"
  after_reply:
    - send_image: images/ticket1.jpg
      caption: "🎫 Билет №1 — действие не ограничено, используем по договоренности!"
    - text: "Готов к следующему шагу?"
  next: q2

q2:
  text: "Помнишь нашу поездку в Казань? Как назывался отель, в котором мы остановились?"
  buttons:
    - text: "Татарская слобода"; next: q3
    - text: "Мираж"; next: q3
    - text: "Корона"; reply: "Умничка! Ты все помнишь! 😍 Держи свой второй билет!"
      after_reply:
        - send_image: images/ticket2.jpg
          caption: "🎫 Билет №2 — за старания тоже дают!"
        - text: "Готов к следующему шагу?"
    - text: "Кристалл"; next: q3
  default_reply:
    - text: "Не совсем! Но ты все равно чудо 💛 Двигаемся дальше!"
    - send_image: images/ticket2.jpg
      caption: "🎫 Билет №2 — за старания тоже дают!"
    - text: "Готов к следующему шагу?"

q3:
  text: "Какое приключение ты бы хотел пережить со мной в ближайшее время? 🌍"
  reply: "Какой бы квест мы ни выбрали — с тобой любое приключение незабываемо ✨"
  after_reply:
    - send_image: images/ticket3.jpg
      caption: "🎫 Билет №3 — для будущих приключений!"
    - text: "Готов к следующему шагу?"
  next: q4

q4:
  text: "Что тебя искренне радует в последнее время (кроме меня, я и так знаю) 😉?"
  reply: "Мне нравится, что ты находишь радость в простых вещах. Это делает тебя особенным ❤️"
  after_reply:
    - send_image: images/ticket4.jpg
      caption: "🎫 Билет №4 — за искренность!"
    - text: "Готов к следующему шагу?"
  next: q5

q5:
  text: "Теперь самое серьезное, напиши, во сколько ты сегодня точно будешь дома?... "
  reply: "Поняла‑поняла, спасибо! Жди сюрприз 🎂 Я тебя обнимаю и люблю больше всего на свете 💖"
  after_reply:
    - send_image: images/ticket5.jpg
      caption: "🎫 Финальный билет — он особенный 💕"
